### ISSUE TITLE
how to ignore some directories?

### ISSUE THREAD

**Issue by craigh** [andstor/copycat-action#20]
I have this job [here
](https://github.com/zikula/core/blob/master/.github/workflows/copy-to-dist.yml#L73-L84):

```yaml
  copy_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Copy config/packages/*
        uses: andstor/copycat-action@v2
        with:
          personal_token: ${{ secrets.COPY_DIST_TOKEN }}
          src_path: /config/packages
          src_filter: '!/test/*|!/dev/*'
          dst_path: /config
          dst_owner: zikula
          dst_repo_name: distribution
```

I am trying to get the copy to ignore `/config/packages/dev` and `/config/packages/test` but clearly the glob pattern is wrong because it isn't working. Can you help?
