### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by yceballost** [andstor/copycat-action#36]
Hi!

I don't understand what is happening when I try to use copycat. This error appears

`fatal: could not read Password for 'https://github.com': No such device or address`

This is my code
```
name: Copy
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: icn_export/
        dst_path: /icn_export/
        dst_owner: yceballost
        dst_repo_name: yceballost.github.io
```

I did a personal token with a lot of permissions but doesn't work.

Thanks
