### ISSUE TITLE
Cleaning a directory

### ISSUE THREAD

**Issue by yceballost** [andstor/copycat-action#39]
I would like to use clean only in a specific folder and keep the rest of the file structure intact.

Actual behaviour:
Is cleaning al my repo and copy just the src_path to dst_path

This is my code

```
name: Copy-New  
on: push  
jobs:  
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.copy_new }}
        src_path: icn_export/
        dst_path: ./
        dst_owner: yceballost
        dst_repo_name: yceballost.github.io
        clean: true
```

Thanks
