### ISSUE TITLE
Add option to copy just folder contents instead of folder AND contents

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [andstor/copycat-action#47]
In my use case I am using GitHub actions to build my Hugo site and would like to use Copycat Action to copy the compiled site directory's contents into the root of my GitHub pages repo. I have Copycat Action working, but it's copying the folder AND it's contents. It would be great if you could add an option to copy just the contents of a folder and not the folder itself. If you know a good workaround I'd also welcome that. I'm pretty new to GitHub Actions but it would definitely help out tremendously.

**Comment by spencer741** [comment]
No need for a PR.

@ressonix (and the two who upvoted this issue: @FrancescoZanti @omarrodriguez15) 

Just looked at the source for `copycat-action`. You can just include a dot at the end of the `src_path`. The dot at the end tells it to copy the contents of the current directory, not the directory itself. Since the author is using `cp`, this makes things predictable. This method also includes hidden files and folders.

```yaml
- name: deploy
  uses: andstor/copycat-action@v3.2.4
  with:
    personal_token: ${{ secrets.GIT_TOKEN }}
    src_path: some/path/.
    dst_path: /.
    dst_owner: spencer741
    dst_repo_name: repo_name
    commit_message: 'New Prod Release'
```

@andstor You can close this issue now. I just tested with one of my actions that is using `copycat-action` and it worked like a charm.
