### ISSUE TITLE
How to use env variables in COMMIT_MESSAGE?

### ISSUE THREAD

**Issue by lens0021** [andstor/copycat-action#48]
I tried this:

```yml
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copycat
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: workflow-templates/extension-test.yml
          dst_path: .github/workflows/test.yml
          dst_owner: lens0021
          dst_repo_name: Sanctions
          dst_branch: master
          commit_message: Update ".github/workflows/test.yml" from ${{ env.GITHUB_REPOSITORY }} (https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }})
```

(results `Update ".github/workflows/test.yml" from (https://github.com//commit/)`)

and this:

```yaml
commit_message: |
  Update ".github/workflows/test.yml"

  from "${{ env.GITHUB_REPOSITORY }}" (https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }}")
```

(results the same)

and this:

```yaml
commit_message: |
  Update ".github/workflows/test.yml"

  from "${{ GITHUB_REPOSITORY }}" (https://github.com/${{ GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }}")
```

(results "The workflow is not valid. .github/workflows/sync-extension-text.yml (Line: 26, Col: 27): Unrecognized named-value: 'GITHUB_REPOSITORY'. Located at position 1 within expression: GITHUB_REPOSITORY")

and this:

```yaml
commit_message: |
  Update ".github/workflows/test.yml"

  from ${GITHUB_REPOSITORY} (https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})
```

(results `Update ".github/workflows/test.yml"`
`from ${GITHUB_REPOSITORY} (https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})`)

```yaml
commit_message: |
  Update ".github/workflows/test.yml"

  from "${GITHUB_REPOSITORY}" (https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})")
```

(results: `Update ".github/workflows/test.yml"`

`from "${GITHUB_REPOSITORY}" https://github.com/"${GITHUB_REPOSITORY}"/commit/"${GITHUB_SHA}"`)

```yaml
commit_message: |
  Update \".github/workflows/test.yml\"

  from ${{ env.GITHUB_REPOSITORY }} (https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }})
```

(results: `Update \".github/workflows/test.yml\"`
  
`from (https://github.com//commit/)`)

or this:
```yaml
commit_message: Update ".github/workflows/test.yml"\n\nfrom ${{ env.GITHUB_REPOSITORY }} (https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }})
```
(results: `Update ".github/workflows/test.yml"\n\nfrom  (https://github.com//commit/)`)

What is the certain way to pass environment variables?

**Comment by lens0021** [comment]
Ok, worked with:
```yaml
steps:
  - run: |
      echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
      echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
  - name: Copycat
    uses: andstor/copycat-action@v3
    with:
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
      src_path: workflow-templates/extension-test.yml
      dst_path: .github/workflows/test.yml
      dst_owner: lens0021
      dst_repo_name: ${{ matrix.repository }}
      dst_branch: ${{ matrix.branch }}
      commit_message: |
        Update ".github/workflows/test.yml"

        from ${{ env.GITHUB_REPOSITORY }} (https://github.com/${{ env.GITHUB_REPOSITORY }}/commit/${{ env.GITHUB_SHA }})
```
