### ISSUE TITLE
Deleting contents of parent folder

### ISSUE THREAD

**Issue by ainsleyclark** [andstor/copycat-action#59]
Hi there,

Thank you for the great action, I use it quite a bit.

I'm having problems with the deletion of particular folders when merging into a repo.
The target repository has a directory structure like so:

```
content
│
└───client-1
│   └───project-1
│       │   index.html
│       │   ...
│   └───project-2
│       │   index.html
│       │   ...
└───client-2
│   └───project-1
│       │   index.html
│       │   ...
```

I copy the source of `public` (source repo) to the client's folder. However, if there are multiple `projects`, it will delete them all.
For example, if `project-1` already resides in the `client-1` folder and `project-2` gets copied, it will delete `project-1`.

I'm using the `clean` flag, I'm not sure if that has anything to do with it? Although I do want to remove the project folder before copying.

```yaml
      # Step 7: Copies the public folder to the staging repo.
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GIT_TOKEN }}
          src_path: public/.
          src_branch: staging
          dst_path: /content/client-1/example-project
          dst_owner: xxxx
          dst_repo_name: xxxx
          clean: true
          commit_message: Update /content/client-1/example-project
```

Thanks for your help in advance.
