### ISSUE TITLE
Can´t exclude multiple folders.

### ISSUE THREAD

**Issue by josesoaresif** [andstor/copycat-action#60]
Can't seem to set multiple paths as exceptions.
This may just be the expected behaviour of the action still, I figured I'd place an issue just in case I'm missing something.
The docs implied that we could do so and I think the glob pattern is correct for excluding everything under controller and view (these are not root folders).

I am using this config:

```
on:
  push:
    branches: [ production ]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        src_path: /admin
        dst_path: /opver3/
        dst_owner: josesoaresif
        dst_repo_name: test01
        dst_branch: main
        src_branch: production
        commit_message: "tests: test commit message"
        username: josesoaresif
        email: josesoares@gmail.com
        clean: true
        exclude: "**/{controller,view}/**/*"
```

works great if you change the exclude to a single folder:
    exclude: "**/controller/**/*"
